project:
  scenario_name: cohesion_burnsev_reduction

workflows:
  landslide_probability:
    sensitivity:
      cohesion_reduction_by_burn_class:
        1: 0.0
        2: 0.15
        3: 0.35
        4: 0.60
